name: Deploy Sovereign Capital

on:
  push:
    branches: [ main ] # سيتم التحديث عند الرفع لفرع main فقط

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 72.62.44.103
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }} # تأكد أن هذا الاسم مطابق للـ Secret
          port: 22
          script: |
            cd /opt/apps/Sovereign_Capital
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            npm run build
            php artisan config:cache
            php artisan optimize:clear